### Variaveis de ambiemte
@base_url = http://127.0.0.1:8000

### Teste de conexao com API

GET {{base_url}}/ HTTP/1.1
Accept: application/json

### Criscao de uma serie
POST  {{base_url}}/ HTTP/1.1
Content-Type: application/json

{
    "titulo": "Rick and Morty",
    "descricão": "Avô e neto em altas aventuras",
    "ano de lancamento": 2013
}

## Obtenção de todas as series
GET  {{base_url}}/series HTTP/1.1
Accept: application/json

PUT {{base_url}}/atualizar HTTP/1.1
Accept: application/json

{
    "titulo": "Rick and Morty",
    "descricão": "Avô e neto em altas aventuras",
    "ano de lancamento": 2013
}   

DELETE {{base_url}}/deletar_serie HTTP/1.1
Accept: application/json
